name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image for armv7
      run: docker buildx build --platform=linux/arm/v7 -t jonolo75/neeo-meta:latest --push .
    - name: Build the Docker image for arm64/v8
      run: docker buildx build --platform=linux/arm64/v8 -t jonolo75/neeo-meta:arm64 --push .
